name: Run freeltcfun.php every 1 minutes

on:
  schedule:
    - cron: '*/1 * * * *' # Setiap 1 menit
  workflow_dispatch:

jobs:
  run-php-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PHP
        run: sudo apt-get update && sudo apt-get install -y php-cli
      - name: Jalankan freeltcfun.php
        run: php freeltcfun.php
